
package vistas;

import main.Libreria;
import java.io.BufferedReader;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.text.ParseException;
import java.text.SimpleDateFormat;// Para manejar fechas con un formato definido
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelos.Cupon;// Modelo de datos que representa un cupón






public class ConsultaCupones extends javax.swing.JFrame {
    // Formato de fecha utilizado en el sistema para los cupones (año-mes-día)
    private final SimpleDateFormat formatoFecha = new SimpleDateFormat("yyyy-MM-dd");

    // Constructor: inicializa componentes y carga datos iniciales
    public ConsultaCupones() {
        initComponents();
        cbTipo.removeAllItems();// Limpia el ComboBox para evitar duplicados
        cbTipo.addItem("porcentaje");
        cbTipo.addItem("monto");
        cargarTabla();
    }
    /**
     * Método que carga los datos de los cupones en la tabla de la interfaz gráfica.
     * Se toma la lista de cupones de Libreria y se muestra en un JTable.
     */
    private void cargarTabla() {
         // Definir las columnas que tendrá la tabla
        String[] columnas = {"Código", "Monto", "Tipo", "Fecha Vencimiento"};
        DefaultTableModel modelo = new DefaultTableModel(columnas, 0); // Crear modelo vacío

         // Recorrer la lista de cupones y agregar cada uno como fila en la tabla
        for (Cupon c : Libreria.cupones) {
             // Convertir la fecha a cadena, si no es nula
            String fechaStr = c.fechaVencimiento != null ? formatoFecha.format(c.fechaVencimiento) : "";
            Object[] fila = {c.codigo, c.monto, c.tipo, fechaStr}; // Crear la fila
            modelo.addRow(fila);// Agregarla al modelo
        }
        // Establecer el modelo de la tabla con los datos cargados
        tablaCupones.setModel(modelo);
    }
    /**
     * Método que guarda la lista actual de cupones en un archivo CSV.
     * @param ruta Ruta del archivo donde se guardarán los datos.
     */
    private void guardarCupones(String ruta) {
        try (PrintWriter pw = new PrintWriter(new FileWriter(ruta))) {
            // Escribir encabezado del archivo
            pw.println("codigo|monto|tipo|fechaVencimiento"); // encabezado
            // Escribir cada cupón en una línea
            for (Cupon c : Libreria.cupones) {
                String fechaStr = c.fechaVencimiento != null ? formatoFecha.format(c.fechaVencimiento) : "";
                pw.println(c.codigo + "|" + c.monto + "|" + c.tipo + "|" + fechaStr);
            }
        } catch (IOException e) {
            JOptionPane.showMessageDialog(this, "Error al guardar el archivo: " + e.getMessage());
        }
    }
     /**
     * Método que carga cupones desde un archivo CSV.
     * Cada línea del archivo representa un cupón con los campos separados por "|".
     * @param ruta Ruta del archivo a leer.
     */
    private void cargarCuponesDesdeArchivo(String ruta) {
        ArrayList<Cupon> lista = new ArrayList<>();// Lista temporal para cargar cupones
        
        try (BufferedReader br = new BufferedReader(new FileReader(ruta))) {
            String linea = br.readLine(); // Leer y omitir el encabezado
            
             // Leer línea por línea el contenido del archivo
            while ((linea = br.readLine()) != null) {
                String[] partes = linea.split("\\|"); // Separar por el delimitador |
                
                if (partes.length >= 4) {
                    Cupon c = new Cupon();
                    c.codigo = partes[0].trim();
                    c.monto = Double.parseDouble(partes[1].trim());
                    c.tipo = partes[2].trim();
                    try {
                        c.fechaVencimiento = formatoFecha.parse(partes[3].trim());
                    } catch (ParseException e) {
                        c.fechaVencimiento = null;// Si hay error de formato, se deja la fecha en null
                    }
                    lista.add(c);// Agregar cupón a la lista
                }
            }
            Libreria.cupones = lista;// Reemplazar la lista original con la nueva
        } catch (FileNotFoundException e) {
            JOptionPane.showMessageDialog(this, "Archivo no encontrado: " + ruta);
        } catch (IOException e) {
            JOptionPane.showMessageDialog(this, "Error al leer el archivo: " + e.getMessage());
        }
    }

   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tablaCupones = new javax.swing.JTable();
        btnEliminar = new javax.swing.JButton();
        btnCargar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        btnCrear = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        txtMonto = new javax.swing.JTextField();
        dateChooser = new com.toedter.calendar.JDateChooser();
        cbTipo = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tablaCupones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tablaCupones);

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnCargar.setText("Cargar");
        btnCargar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCargarActionPerformed(evt);
            }
        });

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        btnCrear.setText("Crear");
        btnCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearActionPerformed(evt);
            }
        });

        jLabel1.setText("Codigo");

        jLabel2.setText("Monto");

        jLabel3.setText("Fecha");

        cbTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel4.setText("Tipo");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addGap(61, 61, 61))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cbTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(34, 34, 34))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnCrear, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnCargar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(55, 55, 55)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(67, 67, 67)
                                .addComponent(txtMonto, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(dateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(11, 11, 11)))))
                .addGap(16, 16, 16))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(69, 69, 69)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(txtMonto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(cbTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(dateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCrear)
                    .addComponent(btnCargar)
                    .addComponent(btnEliminar)
                    .addComponent(btnSalir))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        main.Libreria.guardarTodo(); // <- guarda todo
        this.dispose();
        
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        int filaSeleccionada = tablaCupones.getSelectedRow();
        if (filaSeleccionada >= 0) {
            if (JOptionPane.showConfirmDialog(this, "¿Está seguro de eliminar?") == JOptionPane.YES_OPTION) {
                Libreria.cupones.remove(filaSeleccionada);
                guardarCupones("cupones.csv");
                cargarTabla();
            }
        } else {
            JOptionPane.showMessageDialog(this, "Seleccione un cupón válido para eliminar");
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnCargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCargarActionPerformed
        javax.swing.JFileChooser fileChooser = new javax.swing.JFileChooser();
        fileChooser.setDialogTitle("Seleccione archivo CSV");

        int seleccion = fileChooser.showOpenDialog(this);
        if (seleccion == javax.swing.JFileChooser.APPROVE_OPTION) {
            java.io.File archivo = fileChooser.getSelectedFile();
            cargarCuponesDesdeArchivo(archivo.getAbsolutePath());
            cargarTabla();
        }
    }//GEN-LAST:event_btnCargarActionPerformed

    private void btnCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearActionPerformed
        // TODO add your handling code here
        try {
            String codigo = txtCodigo.getText().trim();
            double monto = Double.parseDouble(txtMonto.getText().trim());
            String tipo = (String) cbTipo.getSelectedItem();
            Date fecha = dateChooser.getDate();

            if (codigo.isEmpty() || fecha == null) {
                JOptionPane.showMessageDialog(this, "Complete todos los campos", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            Cupon nuevo = new Cupon();
            nuevo.codigo = codigo;
            nuevo.monto = monto;
            nuevo.tipo = tipo;
            nuevo.fechaVencimiento = fecha;

            Libreria.cupones.add(nuevo);

            guardarCupones("cupones.csv");
            cargarTabla();

            // Limpiar campos
            txtCodigo.setText("");
            txtMonto.setText("");
            cbTipo.setSelectedIndex(0);
            dateChooser.setDate(null);

        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Monto inválido", "Error", JOptionPane.ERROR_MESSAGE);
        }
       
     
    }//GEN-LAST:event_btnCrearActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCargar;
    private javax.swing.JButton btnCrear;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JComboBox<String> cbTipo;
    private com.toedter.calendar.JDateChooser dateChooser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaCupones;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtMonto;
    // End of variables declaration//GEN-END:variables
}
