/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vistas;

import main.Libreria;
import modelos.Venta;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author mynor
 */
public class ReporteVentas extends javax.swing.JFrame {

    /**
     * Creates new form ReporteVentas
     */
    public ReporteVentas() {
        initComponents();
        this.setLocationRelativeTo(null);
        llenarTabla();

    }

    private void llenarTabla() {
        String[] columnas = {"Cliente", "NIT", "Dirección", "Total", "Total sin IVA", "Vendedor", "Fecha"};
        DefaultTableModel modelo = new DefaultTableModel(columnas, 0);

        for (Venta venta : Libreria.ventas) {
            Object[] fila = new Object[7];
            fila[0] = venta.comprador;
            fila[1] = venta.nit;
            fila[2] = venta.direccion;
            fila[3] = "Q" + venta.total;
            fila[4] = "Q" + venta.totalSinIVA;
            fila[5] = venta.usuarioVendedor != null ? venta.usuarioVendedor.nombre : "Desconocido";
            fila[6] = venta.fecha.toString();
            modelo.addRow(fila);

        }
        tablaReporte.setModel(modelo);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tablaReporte = new javax.swing.JTable();
        btnSalir = new javax.swing.JButton();
        btnExportar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tablaReporte.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tablaReporte);

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        btnExportar.setText("Exportar");
        btnExportar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExportarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnExportar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSalir))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 797, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalir)
                    .addComponent(btnExportar))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        main.Libreria.guardarTodo(); // <- guarda todo
        this.dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnExportarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExportarActionPerformed
        // TODO add your handling code here:
        javax.swing.JFileChooser fileChooser = new javax.swing.JFileChooser();
        fileChooser.setDialogTitle("Guardar reporte de ventas como CSV");

        int seleccion = fileChooser.showSaveDialog(this);
        if (seleccion == javax.swing.JFileChooser.APPROVE_OPTION) {
            java.io.File archivo = fileChooser.getSelectedFile();

            try (java.io.PrintWriter writer = new java.io.PrintWriter(archivo)) {
                writer.println("Cliente|NIT|Dirección|Total|Total sin IVA|Vendedor|Fecha");

                for (int i = 0; i < tablaReporte.getRowCount(); i++) {
                    String cliente = tablaReporte.getValueAt(i, 0).toString();
                    String nit = tablaReporte.getValueAt(i, 1).toString();
                    String direccion = tablaReporte.getValueAt(i, 2).toString();
                    String total = tablaReporte.getValueAt(i, 3).toString();
                    String sinIva = tablaReporte.getValueAt(i, 4).toString();
                    String vendedor = tablaReporte.getValueAt(i, 5).toString();
                    String fecha = tablaReporte.getValueAt(i, 6).toString();

                    writer.println(cliente + "|" + nit + "|" + direccion + "|" + total + "|" + sinIva + "|" + vendedor + "|" + fecha);
                }

                javax.swing.JOptionPane.showMessageDialog(this, "Reporte exportado exitosamente.");
            } catch (Exception e) {
                javax.swing.JOptionPane.showMessageDialog(this, "Error al exportar: " + e.getMessage());
            }
        }
    }//GEN-LAST:event_btnExportarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExportar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaReporte;
    // End of variables declaration//GEN-END:variables
}
