/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vistas;

import javax.swing.table.DefaultTableModel;
import main.Libreria;
import modelos.LibroVenta;
import modelos.Venta;

/**
 *
 * @author Tronquito
 */
public class ReporteLibrosVendidos extends javax.swing.JFrame {

    /**
     * Creates new form ReporteLibrosVendidos
     */
    public ReporteLibrosVendidos() {
        initComponents();
        this.setLocationRelativeTo(null);
        cargarTabla();
    }

    private void cargarTabla() {
        String[] columnas = {"Título", "Cantidad", "Precio Unitario", "Fecha", "Vendedor"};
        DefaultTableModel modelo = new DefaultTableModel(columnas, 0);

        for (Venta venta : Libreria.ventas) {
            for (LibroVenta lv : venta.librosVendidos) {
                Object[] fila = new Object[5];
                fila[0] = lv.titulo;
                fila[1] = lv.cantidad;
                fila[2] = "Q" + lv.precio;
                fila[3] = venta.fecha.toString();
                fila[4] = venta.usuarioVendedor != null ? venta.usuarioVendedor.nombre : "Desconocido";
                modelo.addRow(fila);
            }
        }

        tablaLibros.setModel(modelo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tablaLibros = new javax.swing.JTable();
        btnSalir = new javax.swing.JButton();
        btnExportar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tablaLibros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tablaLibros);

        btnSalir.setText("Cerrar");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        btnExportar.setText("Exportar");
        btnExportar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExportarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 513, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnExportar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSalir)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnExportar)
                    .addComponent(btnSalir))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        main.Libreria.guardarTodo(); // <- guarda todo
        this.dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnExportarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExportarActionPerformed
        // TODO add your handling code here:
        javax.swing.JFileChooser fileChooser = new javax.swing.JFileChooser();
        fileChooser.setDialogTitle("Guardar reporte como CSV");

        int seleccion = fileChooser.showSaveDialog(this);
        if (seleccion == javax.swing.JFileChooser.APPROVE_OPTION) {
            java.io.File archivo = fileChooser.getSelectedFile();

            try (java.io.PrintWriter writer = new java.io.PrintWriter(archivo)) {
                writer.println("Titulo|Cantidad|Precio|Fecha|Vendedor"); // Encabezado

                for (int i = 0; i < tablaLibros.getRowCount(); i++) {
                    String titulo = tablaLibros.getValueAt(i, 0).toString();
                    String cantidad = tablaLibros.getValueAt(i, 1).toString();
                    String precio = tablaLibros.getValueAt(i, 2).toString();
                    String fecha = tablaLibros.getValueAt(i, 3).toString();
                    String vendedor = tablaLibros.getValueAt(i, 4).toString();

                    writer.println(titulo + "|" + cantidad + "|" + precio + "|" + fecha + "|" + vendedor);
                }

                javax.swing.JOptionPane.showMessageDialog(this, "Reporte exportado exitosamente.");
            } catch (Exception e) {
                javax.swing.JOptionPane.showMessageDialog(this, "Error al exportar: " + e.getMessage());
            }
        }
    }//GEN-LAST:event_btnExportarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExportar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaLibros;
    // End of variables declaration//GEN-END:variables
}
